# This file was generated by GoReleaser. DO NOT EDIT.
class Swag < Formula
  desc "Swag gen doc"
  homepage ""
  version "2.2.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/DADDYLAB/swag/releases/download/v2.2.4/swag_2.2.4_Darwin_x86_64.tar.gz"
    sha256 "3300af3341361a8cf14ca1df3c9980942a47260d776653ec27aa2cd7be7a1147"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/DADDYLAB/swag/releases/download/v2.2.4/swag_2.2.4_Linux_x86_64.tar.gz"
      sha256 "50c1849405c054dfc09c3c7158cc946700362767a11bb7573c8116ba2db777a8"
    end
  end

  def install
    system "rm -f #{bin}/swag"
    bin.install "swag"
  end

  def caveats; <<~EOS
    swag init
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
...

  EOS
  end

  test do
    system "#{bin}/swag --version"
  end
end
