# This file was generated by GoReleaser. DO NOT EDIT.
class Swag < Formula
  desc "Swag gen doc"
  homepage ""
  version "2.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/DADDYLAB/swag/releases/download/v2.2.1/swag_2.2.1_Darwin_x86_64.tar.gz"
    sha256 "92e6ffcc3b3b366f0b6829febc635d94ab8b214c9a409f8ac89589b38cdf0222"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/DADDYLAB/swag/releases/download/v2.2.1/swag_2.2.1_Linux_x86_64.tar.gz"
      sha256 "48c0b21b0a9c3c1555afafc04cbdca346b244dd4dc25982aec5ce3eb1e201828"
    end
  end

  def install
    system "rm -f #{bin}/swag"
    bin.install "swag"
  end

  def caveats; <<~EOS
    swag init
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
...

  EOS
  end

  test do
    system "#{bin}/swag --version"
  end
end
