# This file was generated by GoReleaser. DO NOT EDIT.
class Swag < Formula
  desc "Swag gen doc"
  homepage ""
  version "2.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/DADDYLAB/swag/releases/download/v2.1.2/swag_2.1.2_Darwin_x86_64.tar.gz"
    sha256 "5c704387d88f0635acb4cac906b5ec07ce433559afccaa5e18bf11649671ad4a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/DADDYLAB/swag/releases/download/v2.1.2/swag_2.1.2_Linux_x86_64.tar.gz"
      sha256 "1cd6d87e3299bb5c672f6a95f4b27df49410fe40fd005cbb34e2213a2bb8991b"
    end
  end

  def install
    system "rm -f #{bin}/swag"
    bin.install "swag"
  end

  def caveats; <<~EOS
    swag init
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
...

  EOS
  end

  test do
    system "#{bin}/swag --version"
  end
end
